#!/bin/sh

# Devices
mount -t devtmpfs  devtmpfs  /dev
mount -t proc      proc      /proc
mount -t sysfs     sysfs     /sys
mount -t tmpfs     tmpfs     /tmp

# Hello world
sh /bin/hello-world.sh

# Hack for "sh: can't access tty; job control turned off"
setsid  cttyhack sh

exec sh
